global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka:1234'
        labels:
          env: 'local'

  - job_name: 'kafka-streams-challenge'
    static_configs:
      - targets:
          - "kafka-streams-challenge:1234"
        labels:
          env: 'local'

  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets:
          - 'kafka-lag-exporter:9999'
        labels:
          env: 'local'
